GET http://localhost:8080/categories
###
GET http://localhost:8080/categories/1
###
POST http://localhost:8080/categories
Content-Type: application/json

{
"description": "Postres"
}

###
PUT http://localhost:8080/categories/1
Content-Type: application/json

{
"description": "Bebidas"
}
###
DELETE http://localhost:8080/categories/1


###
POST HTTP://localhost:8080/auth/login



### Login: obtener JWT
POST http://localhost:8080/auth/login
Content-Type: application/json

{
"username": "admin",
"password": "admin"
}

### Obtener todas las categorías (requiere JWT, reemplaza el token)
GET http://localhost:8080/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTc0MzYxMTE5NywiaWF0IjoxNzQzNjA3NTk3fQ.lagRR2bX-s6Ly2ox2dT6amZ-Qi6cNyjjPjvm85byD1g
